const { suggestClinicalPath } = require('../routes/recommendations');

const cases = [
    { id: 1, age: 4, gender: 'M', cc: 'High fever with febrile convulsions', findings: 'Temp 40.2°C, no neck stiffness', dr_dx: '—' },
    { id: 2, age: 78, gender: 'F', cc: 'Fall with hip pain and inability to walk', findings: 'X-ray — neck of femur fracture', dr_dx: '—' },
    { id: 3, age: 32, gender: 'M', cc: 'No sleep for 5 days, grandiose plans, elevated mood, excessive spending', findings: 'No substance use', dr_dx: 'Stress' },
    { id: 4, age: 56, gender: 'F', cc: 'Morning stiffness over 1 hour with symmetric small joint swelling', findings: 'ESR 88, RF positive, anti-CCP positive', dr_dx: '—' },
    { id: 5, age: 9, gender: 'M', cc: 'Sore throat, sandpaper rash, strawberry tongue, high fever', findings: '—', dr_dx: 'Viral throat infection' },
    { id: 6, age: 67, gender: 'M', cc: 'Bone pain, fatigue, recurrent infections, backache', findings: 'Hb 7.8, calcium 3.1, protein gap on electrophoresis', dr_dx: 'Age-related anaemia' },
    { id: 7, age: 23, gender: 'F', cc: 'Sudden severe lower abdominal pain, shoulder tip pain, collapse', findings: 'Positive urine pregnancy test, BP 85/55, HR 128', dr_dx: 'Ovarian cyst' },
    { id: 8, age: 44, gender: 'M', cc: 'Frothy urine, bilateral leg and face swelling, fatigue', findings: 'Urine protein ++++, Albumin 2.0, Cholesterol 7.8', dr_dx: '—' },
    { id: 9, age: 13, gender: 'F', cc: 'Excessive thirst, frequent urination, weight loss 5kg in 3 weeks', findings: 'Random glucose 340 mg/dL', dr_dx: 'UTI' },
    { id: 10, age: 71, gender: 'M', cc: 'Urinary hesitancy, weak stream, incomplete emptying, nocturia ×4', findings: 'PSA 41', dr_dx: '—' },
    { id: 11, age: 38, gender: 'F', cc: 'Intermittent blurred vision, tingling in limbs, weakness — episodes over 2 years', findings: 'MRI — multiple periventricular white matter lesions', dr_dx: 'Migraine' },
    { id: 12, age: 25, gender: 'M', cc: 'Knee pain and swelling after twisting during football, unable to fully extend', findings: 'Positive Lachman test, positive pivot shift', dr_dx: '—' },
    { id: 13, age: 60, gender: 'F', cc: 'Change in bowel habits, blood mixed in stool, 3 months', findings: '9kg weight loss, iron deficiency anaemia', dr_dx: 'Haemorrhoids' },
    { id: 14, age: 17, gender: 'M', cc: 'High fever, non-blanching petechial rash, neck stiffness', findings: '—', dr_dx: 'Viral fever' },
    { id: 15, age: 42, gender: 'F', cc: 'Chest tightness with jaw pain on climbing stairs, relieved by rest', findings: 'ECG — ST depression on stress test', dr_dx: '—' },
    { id: 16, age: 5, gender: 'F', cc: 'Stridor at rest, drooling, high fever, muffled voice, tripod position', findings: '—', dr_dx: 'Croup' },
    { id: 17, age: 55, gender: 'M', cc: 'Jaundice, dark urine, pale stools, severe itching, weight loss', findings: 'ALP 920, GGT elevated, CA 19-9 high, dilated CBD on USS', dr_dx: '—' },
    { id: 18, age: 29, gender: 'M', cc: 'Fever, cough, drenching night sweats, 7kg weight loss over 2 months', findings: 'CXR — right apical cavitation', dr_dx: 'Pneumonia' },
    { id: 19, age: 47, gender: 'F', cc: 'Spreading skin blistering with oral mucosa ulcers', findings: 'Nikolsky sign positive', dr_dx: 'Drug allergy' },
    { id: 20, age: 63, gender: 'M', cc: 'Sudden tearing chest pain radiating to the back, maximal at onset', findings: 'BP right arm 170/100, left arm 100/60', dr_dx: 'GERD' },
    { id: 21, age: 34, gender: 'F', cc: 'Easy bruising, spontaneous gum bleeding, heavy periods', findings: 'Platelets 14,000', dr_dx: '—' },
    { id: 22, age: 8, gender: 'M', cc: 'Abdominal pain, vomiting, bloody diarrhea after undercooked BBQ', findings: 'Haemolytic anaemia, elevated creatinine, low platelets', dr_dx: 'Gastroenteritis' },
    { id: 23, age: 58, gender: 'F', cc: 'New-onset severe headache, jaw pain while chewing, scalp tenderness', findings: 'ESR 115, CRP 78', dr_dx: 'Tension headache' },
    { id: 24, age: 26, gender: 'M', cc: 'Sudden painful red eye, haloes around lights, nausea, vomiting', findings: 'IOP 52 mmHg, corneal haze', dr_dx: 'Migraine' },
    { id: 25, age: 52, gender: 'F', cc: 'Weight gain, buffalo hump, purple abdominal striae, facial rounding, mood swings', findings: 'Elevated 24hr urinary cortisol, failed dexamethasone suppression', dr_dx: '—' },
    { id: 26, age: 3, gender: 'F', cc: 'Not walking properly, multiple bruises, long bone tenderness, old fractures on X-ray', findings: '—', dr_dx: 'Clumsy toddler' },
    { id: 27, age: 48, gender: 'M', cc: 'Worst headache of life, sudden onset like a thunderclap, stiff neck', findings: 'CT head normal', dr_dx: 'Tension headache' },
    { id: 28, age: 36, gender: 'F', cc: 'Headache, visual disturbance, ankle swelling at 34 weeks pregnant', findings: 'BP 168/112, urine protein ++', dr_dx: '—' },
    { id: 29, age: 21, gender: 'M', cc: 'Ankle pain and swelling after inversion injury during game', findings: 'Ottawa ankle rules negative', dr_dx: '—' },
    { id: 30, age: 75, gender: 'F', cc: 'Sudden confusion post-op in hospital, agitated', findings: 'Sodium 116', dr_dx: 'Dementia' },
    { id: 31, age: 41, gender: 'M', cc: 'Collapse during 5km run, no prior symptoms', findings: 'ECG — asymmetric septal hypertrophy, left axis deviation', dr_dx: 'Dehydration' },
    { id: 32, age: 30, gender: 'F', cc: 'Intentional paracetamol overdose, 4 hours ago, currently alert', findings: 'Paracetamol level 180 mg/L at 4hrs', dr_dx: '—' },
    { id: 33, age: 66, gender: 'M', cc: 'Progressive breathlessness with dry cough over 18 months, no wheeze', findings: 'Bilateral basal crackles, clubbing, honeycombing on HRCT', dr_dx: 'COPD' },
    { id: 34, age: 19, gender: 'F', cc: 'Collapse after bee sting — facial swelling, wheeze, urticaria', findings: 'BP 68/40, HR 140', dr_dx: '—' },
    { id: 35, age: 53, gender: 'M', cc: 'Epigastric pain relieved by eating, worse when hungry, seasonal variation', findings: 'H. pylori stool antigen positive', dr_dx: '—' },
    { id: 36, age: 7, gender: 'M', cc: 'Recurrent epistaxis, pallor, splenomegaly', findings: 'Hb 6.0, MCV 58, target cells on smear', dr_dx: 'Iron deficiency anaemia' },
    { id: 37, age: 45, gender: 'F', cc: 'Non-tender lump in right breast with skin dimpling, nipple retraction', findings: 'Axillary lymph node enlarged, hard', dr_dx: '—' },
    { id: 38, age: 62, gender: 'M', cc: 'Calf pain on walking 200m, relieved by rest', findings: 'ABI 0.55', dr_dx: 'Muscle cramps' },
    { id: 39, age: 27, gender: 'F', cc: 'Recurring urticaria and lip swelling for 6 weeks, no identifiable trigger', findings: 'Normal complement, normal CBC', dr_dx: '—' },
    { id: 40, age: 35, gender: 'M', cc: 'Unilateral hearing loss, tinnitus, episodic vertigo for 6 months', findings: 'Low-frequency SNHL on audiogram', dr_dx: 'Ear wax' },
    { id: 41, age: 50, gender: 'F', cc: 'Left facial droop with inability to close left eye, loss of taste, hyperacusis', findings: 'Forehead involved, no other neuro signs', dr_dx: '—' },
    { id: 42, age: 16, gender: 'M', cc: 'Painless left testicular swelling with dull back pain, 6 weeks', findings: 'AFP 980, beta-hCG elevated', dr_dx: 'Orchitis' },
    { id: 43, age: 74, gender: 'F', cc: 'Progressive gait disturbance, urinary incontinence, memory loss over 1 year', findings: 'CT — dilated ventricles with normal cortex, no atrophy', dr_dx: 'Alzheimer\'s disease' },
    { id: 44, age: 28, gender: 'M', cc: 'Silver-scaled plaques on elbows, knees, scalp with nail pitting', findings: '—', dr_dx: '—' },
    { id: 45, age: 59, gender: 'M', cc: 'Polyuria, polydipsia, fatigue, blurred vision', findings: 'Fasting glucose 8.1, HbA1c 9.4%', dr_dx: '—' },
    { id: 46, age: 22, gender: 'F', cc: 'Restrictive eating, excessive exercise, lanugo hair, cold extremities', findings: 'BMI 13.2, HR 38, Hb 8.1', dr_dx: 'Anaemia' },
    { id: 47, age: 43, gender: 'M', cc: 'Fever, hepatosplenomegaly, returned from sub-Saharan Africa 10 days ago', findings: 'Thin blood film — ring-form parasites', dr_dx: '—' },
    { id: 48, age: 6, gender: 'F', cc: 'Sudden choking while eating, persistent wheeze, reduced breath sounds right side', findings: 'CXR — right hyperinflation, mediastinal shift', dr_dx: 'Asthma' },
    { id: 49, age: 69, gender: 'F', cc: 'Progressive hoarseness, dysphagia, weight loss, 40-pack-year smoker', findings: 'Firm cervical lymph node', dr_dx: 'GERD' },
    { id: 50, age: 33, gender: 'M', cc: 'Perianal pain with swelling, fever, difficulty sitting', findings: 'Fluctuant tender mass lateral to anus', dr_dx: '—' },
    { id: 51, age: 57, gender: 'F', cc: 'Recurrent kidney stones, constipation, bone pain, depression', findings: 'Calcium 3.1, PTH 148, phosphate low', dr_dx: 'Osteoporosis' },
    { id: 52, age: 11, gender: 'M', cc: 'Sudden onset severe scrotal pain, vomiting, no fever', findings: 'Absent cremasteric reflex, high-riding testis', dr_dx: 'Orchitis' },
    { id: 53, age: 46, gender: 'M', cc: 'Palpitations, weight loss, heat intolerance, lid lag, sweating', findings: 'TSH <0.01, FT4 46, FT3 elevated', dr_dx: '—' },
    { id: 54, age: 24, gender: 'F', cc: 'Two DVTs before age 25, pulmonary embolism, family history of clots', findings: 'Protein C level undetectable', dr_dx: '—' },
    { id: 55, age: 80, gender: 'M', cc: 'Painless rectal bleeding, weight loss, tenesmus, change in stool caliber', findings: 'Hard mass on PR exam', dr_dx: 'Haemorrhoids' },
    { id: 56, age: 39, gender: 'F', cc: 'Recurrent painful oral and genital ulcers, red eye, skin nodules', findings: 'Pathergy test positive', dr_dx: 'Herpes simplex' },
    { id: 57, age: 15, gender: 'F', cc: 'Self-harm marks on wrists, withdrawn, school dropout, persistent low mood 6 months', findings: '—', dr_dx: 'Attention seeking' },
    { id: 58, age: 54, gender: 'M', cc: 'Pill-rolling resting tremor, shuffling gait, mask-like face, stooped posture', findings: 'Cogwheel rigidity, bradykinesia', dr_dx: '—' },
    { id: 59, age: 37, gender: 'F', cc: 'Cyclical pelvic pain, painful intercourse, painful defaecation, infertility 2yrs', findings: 'CA-125 mildly elevated, retroverted uterus on exam', dr_dx: 'Dysmenorrhea' },
    { id: 60, age: 2, gender: 'M', cc: 'Bilious vomiting from day 2 of life, abdominal distension, no meconium', findings: 'Double bubble sign on AXR', dr_dx: 'Colic' },
    { id: 61, age: 31, gender: 'F', cc: 'Recurrent palpitations lasting 30 seconds, near-syncope, young and fit', findings: 'Holter — delta waves, short PR interval', dr_dx: 'Anxiety' },
    { id: 62, age: 64, gender: 'M', cc: 'Massive haemoptysis, history of treated TB 20 years ago, cavity on CXR', findings: 'CXR — upper zone fibrocavitary lesion', dr_dx: '—' },
    { id: 63, age: 18, gender: 'F', cc: 'Severe throat pain, unable to open mouth fully, drooling, hot potato voice', findings: 'Uvula deviated to opposite side, unilateral peritonsillar bulge', dr_dx: 'Tonsillitis' },
    { id: 64, age: 49, gender: 'M', cc: 'Abdominal swelling, jaundice, spider naevi, palmar erythema, heavy alcohol use 20yrs', findings: 'AST:ALT ratio >2, bilirubin 98, INR 1.9', dr_dx: '—' },
    { id: 65, age: 26, gender: 'F', cc: 'Sudden breathlessness and pleuritic chest pain 3 days post caesarean section', findings: 'D-dimer elevated, O2 sat 90%, CTPA ordered', dr_dx: 'Musculoskeletal pain' },
    { id: 66, age: 77, gender: 'F', cc: 'Repeated falls, bradycardia 36bpm, severe constipation, dry skin, cold intolerance', findings: 'TSH 92', dr_dx: 'Old age falls' },
    { id: 67, age: 10, gender: 'M', cc: 'Knee and ankle swelling 2 weeks after sore throat, fever, new heart murmur', findings: 'ASO titre 800, elevated CRP', dr_dx: 'Growing pains' },
    { id: 68, age: 43, gender: 'F', cc: 'Unilateral right-sided headache with nausea, photophobia, phonophobia, relieved by sleep', findings: 'Normal neuro exam, no papilloedema', dr_dx: '—' },
    { id: 69, age: 68, gender: 'M', cc: 'Sudden severe right leg pain, cold, pale, pulseless foot', findings: 'No doppler signal distally, mottled skin', dr_dx: 'Muscle cramp' },
    { id: 70, age: 20, gender: 'M', cc: 'Sudden painless vision loss in right eye, described as curtain falling from top', findings: 'Fundus — retinal detachment', dr_dx: '—' },
    { id: 71, age: 35, gender: 'F', cc: 'Smooth midline neck lump, moves on swallowing, present since childhood', findings: 'Normal thyroid on USS, non-tender', dr_dx: '—' },
    { id: 72, age: 61, gender: 'M', cc: 'Painless frank haematuria ×3 episodes, weight loss, left flank mass', findings: 'CT — 8cm renal mass with vascular invasion', dr_dx: '—' },
    { id: 73, age: 29, gender: 'F', cc: 'Painless vulval ulcer, then generalised macular rash on palms and soles', findings: 'Inguinal lymphadenopathy', dr_dx: 'Drug rash' },
    { id: 74, age: 55, gender: 'M', cc: 'Slurred speech, unsteady gait, worsening over 2 months, family history of same', findings: 'MRI — cerebellar atrophy, no ischaemia', dr_dx: '—' },
    { id: 75, age: 8, gender: 'F', cc: 'Face, hands, feet swelling, frothy urine, no rash, no joint pain', findings: 'Urine protein 3+, Albumin 1.7', dr_dx: 'Allergy' },
    { id: 76, age: 72, gender: 'M', cc: 'Exertional breathlessness, exertional syncope, harsh systolic ejection murmur', findings: 'Echo — aortic valve area 0.65 cm², peak gradient 72 mmHg', dr_dx: '—' },
    { id: 77, age: 44, gender: 'F', cc: 'Persistent dry eyes, dry mouth, parotid swelling, joint pain, fatigue', findings: 'ANA positive, Anti-Ro antibodies positive', dr_dx: 'Depression' },
    { id: 78, age: 19, gender: 'M', cc: 'Anterior knee pain below kneecap worse on stairs, swelling over tibial tuberosity', findings: 'Tender tibial tuberosity, no effusion', dr_dx: '—' },
    { id: 79, age: 58, gender: 'F', cc: 'Postmenopausal vaginal bleeding, 5 episodes over 4 months', findings: 'Endometrial thickness 19mm on USS', dr_dx: 'Atrophic vaginitis' },
    { id: 80, age: 36, gender: 'M', cc: 'HIV positive, fever, dry progressive cough, breathlessness, O2 sat 87%', findings: 'CXR — bilateral ground-glass shadowing', dr_dx: 'Bacterial pneumonia' },
    { id: 81, age: 48, gender: 'M', cc: 'Low mood, anhedonia, insomnia, poor concentration, passive thoughts of death for 3 months', findings: 'No psychosis, no substance use', dr_dx: 'Stress' },
    { id: 82, age: 63, gender: 'F', cc: 'Fatigue, proximal muscle weakness, hypertension, hypokalaemia', findings: 'Urinary potassium wasting, PA ratio elevated, adrenal adenoma on CT', dr_dx: 'Essential hypertension' },
    { id: 83, age: 25, gender: 'M', cc: 'Single painless penile ulcer with clean base, indurated edges, 10 days after new partner', findings: 'Bilateral inguinal lymphadenopathy, non-tender', dr_dx: 'Genital herpes' },
    { id: 84, age: 41, gender: 'F', cc: 'Recurrent mouth ulcers, chronic diarrhea, perianal fistula, colicky pain', findings: 'CRP 72, colonoscopy — skip lesions, cobblestone pattern', dr_dx: 'IBS' },
    { id: 85, age: 82, gender: 'F', cc: 'Found on floor, confused, incontinent, pyrexial', findings: 'WCC 19k, CRP 148, urine nitrites+, leucocytes+', dr_dx: 'Dementia deterioration' },
    { id: 86, age: 33, gender: 'M', cc: 'Multiple abdominal stab wounds, hypotension, tachycardia', findings: 'HR 138, BP 78/48, abdomen rigid', dr_dx: '—' },
    { id: 87, age: 50, gender: 'F', cc: 'Extreme fatigue, pallor, smooth tongue, difficulty swallowing, spoon-shaped nails', findings: 'MCV 64, ferritin 3, serum iron low', dr_dx: '—' },
    { id: 88, age: 45, gender: 'M', cc: 'Persistent low-grade fever, weight loss, generalised lymphadenopathy, night sweats', findings: 'LDH elevated, lymph node firm, non-tender', dr_dx: 'TB' },
    { id: 89, age: 16, gender: 'F', cc: 'Primary amenorrhea, no breast development, short stature, webbed neck', findings: 'FSH and LH very elevated, karyotype 45X0', dr_dx: '—' },
    { id: 90, age: 38, gender: 'M', cc: 'Recurrent palpitations, lightheadedness, father died suddenly at 40', findings: 'ECG — prolonged QTc 520ms', dr_dx: 'Anxiety' },
    { id: 91, age: 68, gender: 'M', cc: 'Sudden chest pain with sweating and vomiting', findings: 'ECG normal', dr_dx: 'Gastritis' },
    { id: 92, age: 24, gender: 'F', cc: 'Lower abdominal pain with missed periods', findings: 'Positive urine pregnancy test', dr_dx: '—' },
    { id: 93, age: 52, gender: 'M', cc: 'Breathlessness at night, orthopnoea, leg swelling', findings: 'BNP 1840', dr_dx: '—' },
    { id: 94, age: 35, gender: 'F', cc: 'Fever with joint pain and butterfly rash on face', findings: 'ANA positive, low complement', dr_dx: 'Viral fever' },
    { id: 95, age: 19, gender: 'M', cc: 'High fever, neck stiffness, photophobia, non-blanching rash', findings: '—', dr_dx: '—' },
    { id: 96, age: 60, gender: 'F', cc: 'Sudden right-sided facial droop, arm weakness, speech difficulty', findings: 'BP 192/114', dr_dx: '—' },
    { id: 97, age: 41, gender: 'M', cc: 'Black tarry stools, dizziness, epigastric pain', findings: 'Hb 7.2, HR 114', dr_dx: 'Acidity' },
    { id: 98, age: 27, gender: 'F', cc: 'Red rash over cheeks worsening in sunlight, joint pain, fatigue', findings: 'ANA positive, anti-dsDNA elevated', dr_dx: '—' },
    { id: 99, age: 33, gender: 'M', cc: 'Sudden breathlessness and pleuritic chest pain 2 days after leg surgery', findings: 'O2 sat 89%, swollen calf', dr_dx: '—' },
    { id: 100, age: 50, gender: 'F', cc: 'Weight loss, palpitations, heat intolerance, diarrhea', findings: 'TSH <0.01', dr_dx: '—' },
    { id: 101, age: 70, gender: 'M', cc: 'Confusion, fever, dysuria', findings: '—', dr_dx: 'Old age' },
    { id: 102, age: 22, gender: 'F', cc: 'Hearing voices, paranoid ideation, social withdrawal for 3 months', findings: 'No substance use, first episode', dr_dx: '—' },
    { id: 103, age: 46, gender: 'M', cc: 'Chronic cough with blood-streaked sputum, 6kg weight loss', findings: 'CXR — hilar enlargement', dr_dx: '—' },
    { id: 104, age: 30, gender: 'F', cc: 'Burning urination, fever, rigors, flank pain, vomiting', findings: '—', dr_dx: '—' },
    { id: 105, age: 65, gender: 'M', cc: 'Chest tightness on exertion, relieves in 5 mins rest', findings: 'Normal resting ECG', dr_dx: 'Muscle pain' },
    { id: 106, age: 14, gender: 'F', cc: 'Fever, joint pain, bleeding gums, petechiae on skin', findings: 'WCC 78k, blast cells on smear', dr_dx: '—' },
    { id: 107, age: 39, gender: 'M', cc: 'Severe epigastric pain radiating to back, worse lying flat, nausea, vomiting', findings: 'Amylase 1800', dr_dx: '—' },
    { id: 108, age: 58, gender: 'F', cc: 'Persistent cough, weight loss 6kg, no fever', findings: 'CXR — lung mass right upper lobe', dr_dx: 'Bronchitis' },
    { id: 109, age: 25, gender: 'M', cc: 'Painful inguinal swelling with skin breakdown and discharge, 3 weeks', findings: 'Multiple sinus tracts, tender matted nodes', dr_dx: '—' },
    { id: 110, age: 72, gender: 'M', cc: 'Gradual memory loss, confusion, personality change over 2 years', findings: 'MMSE 16/30, CT — cortical atrophy', dr_dx: '—' },
    { id: 111, age: 44, gender: 'F', cc: 'Fatigue, pale skin, shortness of breath on exertion', findings: 'Hb 6.8, MCV 110, low B12', dr_dx: '—' },
    { id: 112, age: 31, gender: 'M', cc: 'Sudden severe headache, worst ever, with vomiting, no fever', findings: 'CT head normal', dr_dx: '—' },
    { id: 113, age: 55, gender: 'F', cc: 'Progressive difficulty swallowing solids then liquids, weight loss', findings: 'Barium swallow — irregular narrowing at mid-oesophagus', dr_dx: 'GERD' },
    { id: 114, age: 28, gender: 'F', cc: 'Severe lower abdominal and pelvic pain, fever, vaginal discharge', findings: 'Cervical motion tenderness on exam', dr_dx: '—' },
    { id: 115, age: 62, gender: 'M', cc: 'Reduced urine output, generalised swelling, fatigue', findings: 'Creatinine 580, urea 28, hyperkalemia', dr_dx: '—' },
    { id: 116, age: 18, gender: 'M', cc: 'Fever, exudative sore throat, enlarged cervical lymph nodes, fatigue', findings: 'Splenomegaly, atypical lymphocytes on smear', dr_dx: '—' },
    { id: 117, age: 49, gender: 'F', cc: 'Palpitations, dizziness, occasional near-fainting', findings: 'ECG — absent P waves, irregularly irregular rhythm', dr_dx: '—' },
    { id: 118, age: 36, gender: 'M', cc: 'Sudden severe flank pain radiating to groin, restless, unable to find position', findings: 'Blood in urine on dipstick', dr_dx: '—' },
    { id: 119, age: 63, gender: 'F', cc: 'Back and rib pain, multiple rib fractures from minor trauma', findings: 'Bone biopsy — metastatic adenocarcinoma', dr_dx: '—' },
    { id: 120, age: 21, gender: 'M', cc: 'Fever, red eyes, maculopapular rash, arthralgia, returned from SE Asia', findings: 'Dengue NS1 antigen positive', dr_dx: '—' },
    { id: 121, age: 57, gender: 'M', cc: 'Progressive breathlessness, barrel chest, chronic productive cough, heavy smoker 35yrs', findings: 'FEV1/FVC 0.52, CXR hyperinflation', dr_dx: '—' },
    { id: 122, age: 29, gender: 'F', cc: 'Recurrent colicky abdominal pain, alternating diarrhea and constipation, worse with stress', findings: 'Colonoscopy normal, CRP normal', dr_dx: '—' },
    { id: 123, age: 64, gender: 'M', cc: 'Sudden loss of consciousness, no warning, quick recovery, no tongue biting', findings: 'ECG — complete heart block', dr_dx: '—' },
    { id: 124, age: 26, gender: 'F', cc: 'Patchy hair loss with smooth scalp, no scarring', findings: 'Exclamation mark hairs at periphery', dr_dx: '—' },
    { id: 125, age: 40, gender: 'M', cc: 'Drenching night sweats, weight loss, persistent fatigue, painless neck swelling', findings: 'LDH elevated', dr_dx: '—' },
    { id: 126, age: 53, gender: 'F', cc: 'Persistent hoarseness for 2 months, occasional haemoptysis, smoker', findings: 'Laryngoscopy — left vocal cord lesion', dr_dx: '—' },
    { id: 127, age: 34, gender: 'M', cc: 'Severe crushing chest pain after large meal, radiates to left arm, diaphoretic', findings: 'ECG — ST elevation in II, III, aVF', dr_dx: 'GERD' },
    { id: 128, age: 19, gender: 'F', cc: 'Recurrent panic attacks with palpitations, shortness of breath, fear of dying', findings: 'ECG normal, thyroid normal, no cardiac cause found', dr_dx: '—' },
    { id: 129, age: 61, gender: 'M', cc: 'Painless macroscopic haematuria ×2, no dysuria, smoker', findings: 'Cystoscopy — bladder mucosal lesion', dr_dx: '—' },
    { id: 130, age: 47, gender: 'F', cc: 'Tingling and numbness in both hands, worse at night, relieved by shaking hands', findings: 'Positive Tinel\'s and Phalen\'s test', dr_dx: '—' },
    { id: 131, age: 15, gender: 'M', cc: 'Fever, widespread maculopapular rash, joint pain, swollen lymph nodes', findings: 'Rash began on face, spread to trunk, Koplik spots noted', dr_dx: '—' },
    { id: 132, age: 59, gender: 'F', cc: 'Sudden painless vision loss in left eye, described as curtain from below', findings: 'Fundus — flame-shaped haemorrhages, disc swelling', dr_dx: '—' },
    { id: 133, age: 38, gender: 'M', cc: 'Vomiting bright red blood ×3, known liver disease, alcohol use', findings: 'Haemodynamically unstable, spider naevi', dr_dx: '—' },
    { id: 134, age: 27, gender: 'F', cc: 'Irregular heavy periods, weight gain, acne, excess facial hair', findings: 'USS — polycystic ovaries, LH:FSH >2.5', dr_dx: '—' },
    { id: 135, age: 66, gender: 'M', cc: 'Shuffling gait, difficulty initiating movement, expressionless face, stooped', findings: 'Tremor at rest, positive pull test', dr_dx: '—' },
    { id: 136, age: 45, gender: 'F', cc: 'Right upper quadrant pain after fatty meal, radiates to right shoulder, vomiting', findings: 'USS — gallstones, thickened gallbladder wall', dr_dx: '—' },
    { id: 137, age: 23, gender: 'M', cc: 'Painful urination, yellow penile discharge, 1 week after unprotected intercourse', findings: 'Gram stain — Gram-negative intracellular diplococci', dr_dx: '—' },
    { id: 138, age: 54, gender: 'F', cc: 'Weight gain, cold intolerance, dry skin, constipation, fatigue, depression', findings: 'TSH 64, T4 low', dr_dx: '—' },
    { id: 139, age: 60, gender: 'M', cc: 'Chest pain at rest with sweating, lasting 25 mins', findings: 'ECG — ST elevation V1-V4, troponin rising', dr_dx: '—' },
    { id: 140, age: 11, gender: 'F', cc: 'Recurrent wheezing, nocturnal cough, difficulty breathing on exercise', findings: 'Peak flow variability >20%, good response to salbutamol', dr_dx: '—' },
    { id: 141, age: 6, gender: 'M', cc: 'Fever, ear pain, pulling at ear, irritable, decreased hearing', findings: 'Bulging erythematous tympanic membrane', dr_dx: '—' },
    { id: 142, age: 32, gender: 'F', cc: 'Sudden onset right-sided weakness on waking, slurred speech, age 32', findings: 'MRI — left MCA territory ischaemia, patent foramen ovale found', dr_dx: 'Hemiplegic migraine' },
    { id: 143, age: 14, gender: 'M', cc: 'Hip pain radiating to knee, limp, obese teenager', findings: 'X-ray — widened physis, posterior slippage of femoral head', dr_dx: 'Growing pains' },
    { id: 144, age: 76, gender: 'M', cc: 'Gradual difficulty swallowing saliva, slurred speech, muscle wasting hands, fasciculations', findings: 'Upper and lower motor neuron signs, no sensory loss', dr_dx: 'Stroke' },
    { id: 145, age: 28, gender: 'F', cc: 'Recurrent painful crises in long bones, chest, abdomen since childhood, African origin', findings: 'Hb 7.8, sickling on smear, HbS on electrophoresis', dr_dx: '—' },
    { id: 146, age: 51, gender: 'M', cc: 'Painless jaundice, weight loss, pale stools, new-onset diabetes', findings: 'CA 19-9 greatly elevated, dilated pancreatic duct on CT', dr_dx: 'Viral hepatitis' },
    { id: 147, age: 17, gender: 'F', cc: 'Severe abdominal pain, rigid abdomen, signs of shock, 6 weeks amenorrhea', findings: 'Urine bHCG positive, USS — free fluid, no intrauterine sac', dr_dx: 'Appendicitis' },
    { id: 148, age: 40, gender: 'M', cc: 'Lower back pain worse in morning, stiffness over 1hr, improves with exercise, young male', findings: 'Sacroiliitis on MRI, HLA-B27 positive', dr_dx: 'Mechanical back pain' },
    { id: 149, age: 65, gender: 'F', cc: 'Gradual painless central vision loss, difficulty reading, straight lines appear wavy', findings: 'Drusen on fundoscopy', dr_dx: '—' },
    { id: 150, age: 23, gender: 'M', cc: 'Elevated mood for 3 weeks, stopped sleeping, spent all savings, believes he has special powers', findings: 'No substance use, no psychosis before', dr_dx: '—' },
    { id: 151, age: 47, gender: 'F', cc: 'Breathlessness, leg swelling, frothy cough, orthopnoea', findings: 'CXR — cardiomegaly, upper lobe diversion, Kerley B lines', dr_dx: '—' },
    { id: 152, age: 13, gender: 'M', cc: 'Decreased urine, blood in urine, swollen face and legs, 2 weeks after throat infection', findings: 'Hematuria, RBC casts on microscopy, low complement C3', dr_dx: '—' },
    { id: 153, age: 34, gender: 'M', cc: 'Loin to groin pain, nausea, blood in urine, unable to keep still', findings: 'KUB X-ray — radio-opaque shadow at VUJ', dr_dx: '—' },
    { id: 154, age: 69, gender: 'F', cc: 'Sudden severe vertigo, unable to walk, vomiting, unable to stand', findings: 'MRI — infarct in posterior inferior cerebellar territory', dr_dx: 'Inner ear infection' },
    { id: 155, age: 42, gender: 'M', cc: 'Returned from Thailand, fever every other day with rigors, splenomegaly', findings: 'Thick blood film — P. vivax schizont', dr_dx: '—' },
    { id: 156, age: 28, gender: 'F', cc: 'Target lesion rash after recent antibiotic, some on mucous membranes, eye involvement', findings: 'Peeling of lips, conjunctival injection', dr_dx: 'Drug allergy' },
    { id: 157, age: 56, gender: 'M', cc: 'Persistent cough, haemoptysis, voice change, weight loss, smoker 30yrs', findings: 'CT — 4cm spiculated right upper lobe mass', dr_dx: '—' },
    { id: 158, age: 31, gender: 'F', cc: 'Recurrent binge eating followed by self-induced vomiting, tooth enamel erosion, normal BMI', findings: 'Hypokalaemia, elevated amylase (parotid)', dr_dx: 'Depression' },
    { id: 159, age: 73, gender: 'M', cc: 'Acute severe lower back pain, pulsatile abdominal mass, hypotension', findings: 'USS — 8cm AAA', dr_dx: 'Renal colic' },
    { id: 160, age: 20, gender: 'F', cc: 'Fever, sore throat, fatigue, rash appearing after amoxicillin', findings: 'Atypical lymphocytes, splenomegaly, monospot positive', dr_dx: '—' },
    { id: 161, age: 48, gender: 'M', cc: 'Fast-growing dark irregular skin lesion on upper back, irregular border, multiple colours', findings: 'ABCDE criteria positive', dr_dx: '—' },
    { id: 162, age: 59, gender: 'F', cc: 'Hypercalcaemia, kidney stones, low mood, bone pain, peptic ulcer disease together', findings: 'Elevated PTH, low phosphate, PTHrP normal', dr_dx: '—' },
    { id: 163, age: 26, gender: 'M', cc: 'Fever, productive cough, pleuritic chest pain, dullness to percussion right base', findings: 'WCC 18k, CXR — right basal consolidation with effusion', dr_dx: '—' },
    { id: 164, age: 37, gender: 'F', cc: 'Severe one-sided headache with eye redness, ptosis, small pupil on same side', findings: 'No neurological deficit, normal CT', dr_dx: 'Cluster headache' },
    { id: 165, age: 12, gender: 'M', cc: 'Limp, fever, reluctance to move hip, ill-looking child', findings: 'ESR 80, WCC 18k, hip USS — effusion', dr_dx: 'Transient synovitis' },
    { id: 166, age: 55, gender: 'F', cc: 'Bilateral shoulder and hip girdle aching, stiffness, age over 50, rapid ESR rise', findings: 'ESR 98, CRP 60, dramatic response to steroids', dr_dx: '—' },
    { id: 167, age: 22, gender: 'M', cc: 'Sudden severe scrotal swelling and pain after minor trauma, young male', findings: 'USS doppler — absent testicular blood flow', dr_dx: 'Epididymo-orchitis' },
    { id: 168, age: 65, gender: 'M', cc: 'Exertional dyspnea, ankle swelling, elevated JVP, displaced apex', findings: 'Echo — EF 28%, dilated LV', dr_dx: '—' },
    { id: 169, age: 30, Bird: 'F', cc: 'Butterfly facial rash, joint pain, hair loss, photosensitivity, oral ulcers', findings: 'ANA 1:640, anti-dsDNA positive, low C3/C4, proteinuria', dr_dx: 'Eczema' },
    { id: 170, age: 43, gender: 'M', cc: 'Productive morning cough, 3 cups of sputum daily, recurrent chest infections since childhood', findings: 'CXR — lower lobe bronchiectatic changes, sputum culture — Pseudomonas', dr_dx: '—' },
    { id: 171, age: 18, gender: 'M', cc: 'Intermittent giving way and locking of knee, effusion, positive McMurray test', findings: 'MRI — medial meniscal bucket-handle tear', dr_dx: '—' },
    { id: 172, age: 60, gender: 'F', cc: 'Itching, fatigue, dark urine, positive AMA titre', findings: 'Elevated ALP, normal bili, anti-mitochondrial antibody M2 subtype positive', dr_dx: 'GERD' },
    { id: 173, age: 5, gender: 'M', cc: 'Swollen red warm knee, fever, won\'t walk, no trauma', findings: 'WCC 24k, ESR 90, CRP 82, joint fluid — turbid, WCC 80k', dr_dx: 'Viral arthritis' },
    { id: 174, age: 38, gender: 'F', cc: 'Fatigue, joint pain, photosensitive rash, pleuritis, mouth ulcers, alopecia', findings: 'ANA positive, proteinuria, thrombocytopaenia', dr_dx: 'Viral illness' },
    { id: 175, age: 76, gender: 'M', cc: 'Sudden onset dense left hemiplegia, facial droop, slurred speech, onset 2 hours ago', findings: 'CT head — no haemorrhage, NIHSS 18', dr_dx: '—' },
    { id: 176, age: 24, gender: 'F', cc: 'Right iliac fossa pain, fever, adnexal tenderness, cervical excitation, sexually active', findings: 'Elevated WCC, USS — right adnexal mass 4cm', dr_dx: 'Appendicitis' },
    { id: 177, age: 51, gender: 'M', cc: 'Fever, sharp chest pain worse on leaning back, pericardial rub on auscultation', findings: 'ECG — saddle-shaped ST elevation in all leads', dr_dx: '—' },
    { id: 178, age: 9, gender: 'F', cc: 'Jaundice, dark urine, abdominal pain, haemolytic anaemia triggered by infection', findings: 'G6PD deficiency on enzyme assay', dr_dx: '—' },
    { id: 179, age: 37, gender: 'M', cc: 'Chronic diarrhea, weight loss, bloating, after wheat-containing meals, anaemia', findings: 'Anti-TTG IgA positive, duodenal biopsy — villous atrophy', dr_dx: 'IBS' },
    { id: 180, age: 66, gender: 'F', cc: 'New onset seizure, headache, progressive right-sided weakness over 4 weeks', findings: 'MRI — ring-enhancing lesion with surrounding oedema, known lung cancer', dr_dx: 'Stroke' },
    { id: 181, age: 29, gender: 'M', cc: 'Low back pain radiating down left leg to foot, worse coughing, positive SLR at 30°', findings: 'MRI — L4/5 disc prolapse compressing L5 nerve root', dr_dx: '—' },
    { id: 182, age: 53, gender: 'F', cc: 'Breathlessness, dry cough, weight loss, no smoking, works in stone cutting factory', findings: 'CXR — upper lobe nodular shadowing, eggshell lymph node calcification', dr_dx: 'TB' },
    { id: 183, age: 41, gender: 'M', cc: 'Severe headache, fever, photophobia, vomiting, confused, petechial rash', findings: 'LP — turbid CSF, neutrophilia, low glucose', dr_dx: '—' },
    { id: 184, age: 67, gender: 'F', cc: 'Increasing leg swelling, dyspnoea, elevated JVP, clear lung fields', findings: 'Echo — reduced right heart function, estimated RVSP 72 mmHg', dr_dx: 'Heart failure' },
    { id: 185, age: 31, gender: 'M', cc: 'Gradually enlarging painless lump in left neck, low-grade fever, night sweats, itch', findings: 'Excisional biopsy — Reed-Sternberg cells', dr_dx: 'Reactive lymphadenopathy' },
    { id: 186, age: 46, gender: 'F', cc: 'Double vision, drooping eyelid worse in evenings, difficulty swallowing', findings: 'Edrophonium test positive, anti-AChR antibodies positive', dr_dx: 'Stroke' },
    { id: 187, age: 58, gender: 'M', cc: 'Upper GI bleed, known cirrhosis, haematemesis of fresh blood, spider naevi', findings: 'HR 126, BP 88/52, OGD — varices', dr_dx: '—' },
    { id: 188, age: 7, gender: 'M', cc: 'Swollen painful joints, fever, salmon-coloured evanescent rash, quotidian fever pattern', findings: 'Very high ferritin 8400, elevated WCC', dr_dx: 'Growing pains' },
    { id: 189, age: 34, gender: 'F', cc: 'Fatigue, jaundice, dark urine after cold exposure', findings: 'Cold agglutinins positive, DAT positive, spherocytes on smear', dr_dx: 'Viral hepatitis' },
    { id: 190, age: 71, gender: 'M', cc: 'Bone pain, weight loss, elevated PSA 340, raised alkaline phosphatase', findings: 'Bone scan — multiple hot spots spine and pelvis', dr_dx: '—' },
    { id: 191, age: 20, gender: 'F', cc: 'Status epilepticus, known epileptic, stopped medication 3 days ago', findings: 'Actively fitting on arrival', dr_dx: '—' },
    { id: 192, age: 48, gender: 'M', cc: 'Dysphagia, regurgitation of undigested food, weight loss, gurgling in neck', findings: 'Barium swallow — posterior pharyngeal pouch', dr_dx: 'GERD' },
    { id: 193, age: 55, gender: 'F', cc: 'Pelvic heaviness, urinary frequency, visible bulge at vaginal opening', findings: 'Uterine prolapse grade III on exam', dr_dx: '—' },
    { id: 194, age: 26, gender: 'M', cc: 'Painful eye with reduced vision, photophobia, floaters in young adult', findings: 'Keratic precipitates, cells and flare in anterior chamber', dr_dx: 'Conjunctivitis' },
    { id: 195, age: 39, gender: 'F', cc: 'Episodic severe headache, sweating, palpitations, hypertensive crisis in attacks', findings: '24hr urinary catecholamines elevated, adrenal mass on CT', dr_dx: 'Essential hypertension' },
    { id: 196, age: 62, gender: 'M', cc: 'Left arm and leg weakness over 20 mins, speech difficulty, fully resolved in 1 hour', findings: 'MRI DWI — no acute infarct yet', dr_dx: 'Migraine' },
    { id: 197, age: 30, gender: 'F', cc: 'Postpartum 3 weeks — hearing voices telling her to harm baby, not sleeping, confused', findings: 'No prior psychiatric history', dr_dx: 'Postnatal blues' },
    { id: 198, age: 45, gender: 'M', cc: 'Sudden severe pain and swelling of right big toe overnight, cannot bear bed sheet touching it', findings: 'Serum uric acid 640 μmol/L, crystals in joint aspirate', dr_dx: 'Cellulitis' },
    { id: 199, age: 17, gender: 'M', cc: 'Road traffic accident, chest trauma, severe dyspnoea, trachea deviated to left', findings: 'Absent breath sounds right side, hypotension', dr_dx: 'Pneumonia' },
    { id: 200, age: 58, gender: 'F', cc: 'Fatigue, weight gain, loss of outer third of eyebrow, bradycardia, periorbital puffiness', findings: 'TSH 78, free T4 low, cholesterol elevated', dr_dx: 'Depression' }
];

async function runBenchmark() {
    console.log(`🚀 [Ultimate Stress Test - All 200 Cases] Starting clinical evaluation...\n`);
    
    for (const c of cases) {
        try {
            const result = await suggestClinicalPath(c.cc, c.findings, { age: c.age, gender: c.gender });
            
            const diffs = (result.differentials || []).join(', ');
            const invs = (result.investigations.primary || []).concat(result.investigations.secondary || []).join(', ');
            const meds = result.recommendations.map(r => r.drug.toUpperCase()).join(', ') || 'NONE';
            const advice = result.advice.replace(/\n•/g, ' | •');

            console.log(`✅ **Case ${c.id} (${c.cc})**: 🔍 Diagnosis: ${result.probable_diagnosis} ⚖️ Differentials: ${diffs} 🧪 Investigations: ${invs} 💊 Medicines: ${meds} 📝 Advice: ${advice} | 🎯 Confidence: ${Math.round(result.confidence * 100)}%`);
        } catch (err) {
            console.log(`❌ ERROR on Case ${c.id}: ${err.message}`);
        }
    }
}

runBenchmark();
